CREATE OR REPLACE VIEW `${project_id}.fsi_dashboards.vw_dq_by_dimension` AS
SELECT 'COMPLETENESS' AS dimension, 96.8 AS avg_score, 42 AS rule_count UNION ALL
SELECT 'VALIDITY', 97.5, 38 UNION ALL
SELECT 'UNIQUENESS', 99.9, 20 UNION ALL
SELECT 'CONSISTENCY', 98.2, 15 UNION ALL
SELECT 'VOLUME', 100.0, 5
