CREATE OR REPLACE TABLE `${project_id}.fsi_reference.ref_isin_mapping` AS
SELECT
  CONCAT('US', LPAD(CAST(MOD(n * 7, 1000000000) AS STRING), 9, '0'), CAST(MOD(n, 10) AS STRING)) AS isin,
  LPAD(CAST(MOD(n * 7, 1000000000) AS STRING), 9, '0') AS cusip,
  'US' AS country_code,
  CASE MOD(n, 3) WHEN 0 THEN 'NYSE' WHEN 1 THEN 'NASDAQ' ELSE 'OTC' END AS exchange
FROM UNNEST(GENERATE_ARRAY(1, 5000)) AS n
