CREATE OR REPLACE TABLE `${project_id}.fsi_bronze.bronze_audit_events` AS
SELECT
  CONCAT('AUD-', LPAD(CAST(n AS STRING), 10, '0')) AS audit_event_id,
  TIMESTAMP_ADD(TIMESTAMP '2024-01-01 00:00:00 UTC', INTERVAL CAST(FLOOR(RAND() * 500 * 24 * 60) AS INT64) MINUTE) AS event_timestamp,
  CONCAT('EMP-', LPAD(CAST(CAST(FLOOR(RAND() * 5000) + 1 AS INT64) AS STRING), 6, '0')) AS user_id,
  CASE MOD(n, 8) WHEN 0 THEN 'LOGIN' WHEN 1 THEN 'LOGOUT' WHEN 2 THEN 'DATA_ACCESS' WHEN 3 THEN 'DATA_MODIFY' WHEN 4 THEN 'REPORT_RUN' WHEN 5 THEN 'EXPORT' WHEN 6 THEN 'APPROVAL' ELSE 'CONFIG_CHANGE' END AS event_type,
  CASE MOD(n, 6) WHEN 0 THEN 'ATLAS' WHEN 1 THEN 'FORTUNA' WHEN 2 THEN 'ARGUS' WHEN 3 THEN 'BigQuery' WHEN 4 THEN 'Email' ELSE 'Portal' END AS system_name,
  CASE MOD(n, 5) WHEN 0 THEN 'Customer Records' WHEN 1 THEN 'Account Data' WHEN 2 THEN 'Loan Files' WHEN 3 THEN 'Financial Reports' ELSE 'Trade Data' END AS resource_accessed,
  CASE MOD(n, 3) WHEN 0 THEN 'Success' WHEN 1 THEN 'Success' ELSE CASE WHEN MOD(n, 20) = 0 THEN 'Failed' ELSE 'Success' END END AS result,
  CONCAT(CAST(FLOOR(RAND() * 255) AS STRING), '.', CAST(FLOOR(RAND() * 255) AS STRING), '.', CAST(FLOOR(RAND() * 255) AS STRING), '.', CAST(FLOOR(RAND() * 255) AS STRING)) AS source_ip,
  CASE WHEN MOD(n, 10) = 0 THEN TRUE ELSE FALSE END AS sox_relevant,
  TIMESTAMP_ADD(TIMESTAMP '2024-01-01 00:00:00 UTC', INTERVAL CAST(FLOOR(RAND() * 500 * 24 * 60) AS INT64) MINUTE) AS created_at,
  'ARGUS' AS source_system
FROM UNNEST(GENERATE_ARRAY(1, 30000)) AS n
