CREATE OR REPLACE TABLE `${project_id}.fsi_bronze.bronze_securities` AS
SELECT
  CONCAT('SEC-', LPAD(CAST(n AS STRING), 6, '0')) AS security_id,
  UPPER(CONCAT(
    CASE MOD(n, 26) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'C' WHEN 3 THEN 'D' WHEN 4 THEN 'E' WHEN 5 THEN 'F' WHEN 6 THEN 'G' WHEN 7 THEN 'H' WHEN 8 THEN 'I' WHEN 9 THEN 'J' WHEN 10 THEN 'K' WHEN 11 THEN 'L' WHEN 12 THEN 'M' WHEN 13 THEN 'N' WHEN 14 THEN 'O' WHEN 15 THEN 'P' WHEN 16 THEN 'Q' WHEN 17 THEN 'R' WHEN 18 THEN 'S' WHEN 19 THEN 'T' WHEN 20 THEN 'U' WHEN 21 THEN 'V' WHEN 22 THEN 'W' WHEN 23 THEN 'X' WHEN 24 THEN 'Y' ELSE 'Z' END,
    CASE MOD(CAST(FLOOR(n/26) AS INT64), 26) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'C' WHEN 3 THEN 'D' WHEN 4 THEN 'E' WHEN 5 THEN 'F' WHEN 6 THEN 'G' WHEN 7 THEN 'H' WHEN 8 THEN 'I' WHEN 9 THEN 'J' WHEN 10 THEN 'K' WHEN 11 THEN 'L' WHEN 12 THEN 'M' WHEN 13 THEN 'N' WHEN 14 THEN 'O' WHEN 15 THEN 'P' WHEN 16 THEN 'Q' WHEN 17 THEN 'R' WHEN 18 THEN 'S' WHEN 19 THEN 'T' WHEN 20 THEN 'U' WHEN 21 THEN 'V' WHEN 22 THEN 'W' WHEN 23 THEN 'X' WHEN 24 THEN 'Y' ELSE 'Z' END,
    CASE MOD(CAST(FLOOR(n/676) AS INT64), 26) WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'C' WHEN 3 THEN 'D' WHEN 4 THEN 'E' WHEN 5 THEN 'F' WHEN 6 THEN 'G' WHEN 7 THEN 'H' ELSE 'X' END
  )) AS ticker,
  CONCAT('Security ', CAST(n AS STRING)) AS security_name,
  CONCAT(LPAD(CAST(MOD(n * 7, 1000000000) AS STRING), 9, '0')) AS cusip,
  CONCAT('US', LPAD(CAST(MOD(n * 7, 1000000000) AS STRING), 9, '0'), CAST(MOD(n, 10) AS STRING)) AS isin,
  CASE MOD(n, 8)
    WHEN 0 THEN 'Common Stock' WHEN 1 THEN 'Preferred Stock' WHEN 2 THEN 'Corporate Bond'
    WHEN 3 THEN 'Treasury Bond' WHEN 4 THEN 'Municipal Bond' WHEN 5 THEN 'ETF'
    WHEN 6 THEN 'Mutual Fund' ELSE 'Money Market'
  END AS security_type,
  CASE MOD(n, 8)
    WHEN 0 THEN 'Equity' WHEN 1 THEN 'Equity' WHEN 2 THEN 'Fixed Income'
    WHEN 3 THEN 'Fixed Income' WHEN 4 THEN 'Fixed Income' WHEN 5 THEN 'Equity'
    WHEN 6 THEN 'Equity' ELSE 'Cash'
  END AS asset_class,
  CASE MOD(n, 11)
    WHEN 0 THEN 'Technology' WHEN 1 THEN 'Healthcare' WHEN 2 THEN 'Financial Services'
    WHEN 3 THEN 'Consumer Discretionary' WHEN 4 THEN 'Industrials' WHEN 5 THEN 'Energy'
    WHEN 6 THEN 'Utilities' WHEN 7 THEN 'Real Estate' WHEN 8 THEN 'Materials'
    WHEN 9 THEN 'Communication Services' ELSE 'Consumer Staples'
  END AS sector,
  CASE MOD(n, 5) WHEN 0 THEN 'US' WHEN 1 THEN 'US' WHEN 2 THEN 'GB' WHEN 3 THEN 'JP' ELSE 'DE' END AS country,
  'USD' AS currency,
  CASE MOD(n, 8) WHEN 0 THEN 'NYSE' WHEN 1 THEN 'NASDAQ' WHEN 2 THEN 'OTC' WHEN 3 THEN 'TREASURY' WHEN 4 THEN 'MUNI' WHEN 5 THEN 'NYSE' WHEN 6 THEN 'NASDAQ' ELSE 'MONEY_MARKET' END AS exchange,
  ROUND(0.5 + RAND() * 5000, 2) AS last_price,
  ROUND(CASE WHEN MOD(n, 8) IN (0, 1, 5, 6) THEN RAND() * 5 ELSE 0 END, 2) AS dividend_yield,
  CASE WHEN MOD(n, 8) IN (2, 3, 4) THEN ROUND(0.01 + RAND() * 0.08, 4) ELSE NULL END AS coupon_rate,
  CASE WHEN MOD(n, 8) IN (2, 3, 4) THEN DATE_ADD('2025-01-01', INTERVAL CAST(FLOOR(RAND() * 10000) AS INT64) DAY) ELSE NULL END AS maturity_date,
  CASE WHEN MOD(n, 8) IN (2, 3, 4) THEN CASE MOD(n, 4) WHEN 0 THEN 'AAA' WHEN 1 THEN 'AA' WHEN 2 THEN 'A' ELSE 'BBB' END ELSE NULL END AS credit_rating,
  TIMESTAMP_ADD(TIMESTAMP '2024-01-01 00:00:00 UTC', INTERVAL CAST(FLOOR(RAND() * 500 * 24 * 60) AS INT64) MINUTE) AS created_at,
  'FORTUNA' AS source_system
FROM UNNEST(GENERATE_ARRAY(1, 5000)) AS n
