CREATE OR REPLACE TABLE `${project_id}.fsi_bronze.bronze_fx_rates` AS
SELECT
  CONCAT('FX-', LPAD(CAST(n AS STRING), 8, '0')) AS fx_rate_id,
  DATE_ADD('2023-01-01', INTERVAL CAST(FLOOR(n / 8.0) AS INT64) DAY) AS as_of_date,
  CASE MOD(n, 8)
    WHEN 0 THEN 'EUR/USD' WHEN 1 THEN 'GBP/USD' WHEN 2 THEN 'USD/JPY'
    WHEN 3 THEN 'USD/CHF' WHEN 4 THEN 'USD/CAD' WHEN 5 THEN 'AUD/USD'
    WHEN 6 THEN 'USD/MXN' ELSE 'USD/CNY'
  END AS currency_pair,
  ROUND(CASE MOD(n, 8)
    WHEN 0 THEN 1.05 + RAND() * 0.15 WHEN 1 THEN 1.20 + RAND() * 0.15 WHEN 2 THEN 130 + RAND() * 30
    WHEN 3 THEN 0.85 + RAND() * 0.1 WHEN 4 THEN 1.25 + RAND() * 0.15 WHEN 5 THEN 0.63 + RAND() * 0.1
    WHEN 6 THEN 16 + RAND() * 3 ELSE 7.0 + RAND() * 0.5
  END, 6) AS mid_rate,
  ROUND(CASE MOD(n, 8)
    WHEN 0 THEN 1.05 + RAND() * 0.15 - 0.001 ELSE 0.001
  END, 6) AS bid_rate,
  ROUND(CASE MOD(n, 8)
    WHEN 0 THEN 1.05 + RAND() * 0.15 + 0.001 ELSE 0.001
  END, 6) AS ask_rate,
  CASE MOD(n, 3) WHEN 0 THEN 'Bloomberg' WHEN 1 THEN 'Reuters' ELSE 'ECB' END AS source,
  TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL CAST(FLOOR(RAND() * 500 * 24 * 60) AS INT64) MINUTE) AS created_at,
  'ARGUS' AS source_system
FROM UNNEST(GENERATE_ARRAY(1, 5000)) AS n
